// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: followers.sql

package sqlc

import (
	"context"
)

const follow = `-- name: Follow :exec
INSERT INTO
    followers (user_id, follower_id)
VALUES
    ($1, $2)
`

type FollowParams struct {
	UserID     int64 `json:"user_id"`
	FollowerID int64 `json:"follower_id"`
}

func (q *Queries) Follow(ctx context.Context, arg FollowParams) error {
	_, err := q.db.ExecContext(ctx, follow, arg.UserID, arg.FollowerID)
	return err
}

const unfollow = `-- name: Unfollow :exec
DELETE FROM followers
WHERE
    user_id = $1
    AND follower_id = $2
`

type UnfollowParams struct {
	UserID     int64 `json:"user_id"`
	FollowerID int64 `json:"follower_id"`
}

func (q *Queries) Unfollow(ctx context.Context, arg UnfollowParams) error {
	_, err := q.db.ExecContext(ctx, unfollow, arg.UserID, arg.FollowerID)
	return err
}
