// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package sqlc

import (
	"context"
	"database/sql"
)

type Querier interface {
	CreateComment(ctx context.Context, arg CreateCommentParams) (CreateCommentRow, error)
	CreatePost(ctx context.Context, arg CreatePostParams) (Post, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	CreateUserVerification(ctx context.Context, arg CreateUserVerificationParams) (UserVerification, error)
	DeletePost(ctx context.Context, id int64) error
	DeleteUser(ctx context.Context, id int64) error
	DeleteUserVerification(ctx context.Context, userID int64) error
	Follow(ctx context.Context, arg FollowParams) error
	GetCommentsByPostID(ctx context.Context, postID int64) ([]GetCommentsByPostIDRow, error)
	GetPostByID(ctx context.Context, id int64) (Post, error)
	GetRoleByName(ctx context.Context, name string) (GetRoleByNameRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id int64) (User, error)
	GetUserFeed(ctx context.Context, arg GetUserFeedParams) ([]GetUserFeedRow, error)
	GetUserFromInvitation(ctx context.Context, arg GetUserFromInvitationParams) (GetUserFromInvitationRow, error)
	Unfollow(ctx context.Context, arg UnfollowParams) error
	UpdatePost(ctx context.Context, arg UpdatePostParams) (sql.NullInt32, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
}

var _ Querier = (*Queries)(nil)
