// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: roles.sql

package sqlc

import (
	"context"
)

const getRoleByName = `-- name: GetRoleByName :one
SELECT
    id, name, level, description
FROM
    roles
WHERE
    name = $1
`

func (q *Queries) GetRoleByName(ctx context.Context, name string) (Role, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, name)
	var i Role
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Level,
		&i.Description,
	)
	return i, err
}
