// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"database/sql"
	"time"
)

type Comment struct {
	ID        int64     `json:"id"`
	PostID    int64     `json:"post_id"`
	UserID    int64     `json:"user_id"`
	Content   string    `json:"content"`
	CreatedAt time.Time `json:"created_at"`
}

type Follower struct {
	UserID     int64     `json:"user_id"`
	FollowerID int64     `json:"follower_id"`
	CreatedAt  time.Time `json:"created_at"`
}

type Post struct {
	ID        int64         `json:"id"`
	Title     string        `json:"title"`
	UserID    int64         `json:"user_id"`
	Content   string        `json:"content"`
	CreatedAt time.Time     `json:"created_at"`
	UpdatedAt time.Time     `json:"updated_at"`
	Tags      []string      `json:"tags"`
	Version   sql.NullInt32 `json:"version"`
}

type Role struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Level       int32          `json:"level"`
	Description sql.NullString `json:"description"`
}

type User struct {
	ID         int64     `json:"id"`
	Email      string    `json:"email"`
	Username   string    `json:"username"`
	Password   []byte    `json:"password"`
	CreatedAt  time.Time `json:"created_at"`
	IsVerified bool      `json:"is_verified"`
	RoleID     int32     `json:"role_id"`
}

type UserVerification struct {
	Token  []byte    `json:"token"`
	UserID int64     `json:"user_id"`
	Expiry time.Time `json:"expiry"`
}
