// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: roles.sql

package db

import (
	"context"
	"database/sql"
)

const getRoleByName = `-- name: GetRoleByName :one
SELECT
    id,
    name,
    description,
    level
FROM
    roles
WHERE
    name = $1
`

type GetRoleByNameRow struct {
	ID          int64          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Level       int32          `json:"level"`
}

func (q *Queries) GetRoleByName(ctx context.Context, name string) (GetRoleByNameRow, error) {
	row := q.db.QueryRowContext(ctx, getRoleByName, name)
	var i GetRoleByNameRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.Level,
	)
	return i, err
}
